import Link from "next/link"
import { ArrowLeft } from "lucide-react"

import { Button } from "@/components/ui/button"

export default function TermsAndConditionsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8  text-gray-900 dark:text-gray-50">
    <h1 className="text-3xl font-bold text-center text-primary mb-6">Terms and Conditions</h1>
    
    <p className="mb-4">
      Welcome to <strong>CourierWallah</strong>, the digital version of Elegant Courier Service! Before using our website and services, please carefully review these terms and conditions. By accessing and using our website, you agree to be bound by these terms. If you do not agree with any part of these terms, please refrain from using our website and services.
    </p>

    <section title="Definitions">
      <ul className="list-disc list-inside space-y-1">
        <li><strong>"We," "Us," or "CourierWallah"</strong> refers to the digital platform providing courier services in association with Elegant Courier Service.</li>
        <li><strong>"You" or "User"</strong> refers to any individual or entity using our website or services.</li>
      </ul>
    </section>

    <section title="Use of Our Website">
      <ul className="list-disc list-inside space-y-1">
        <li>You must be at least 15 years old to use our website and services.</li>
        <li>You are responsible for providing accurate and complete information during the registration or booking process.</li>
        <li>Booking of courier services can be done through our website, and invoices will be generated by Elegant Courier Service.</li>
        <li>We also facilitate bookings through third-party partners such as DTDC, XpressBees, Dhelivery, or Elegant Courier Service, depending on availability and region.</li>
      </ul>
    </section>

    <section title="Courier Services">
      <ul className="list-disc list-inside space-y-1">
        <li>We act as an intermediary between you and Elegant Courier Service or third-party courier partners.</li>
        <li>Delivery times are approximate and subject to change due to weather, traffic, or other unforeseen events.</li>
        <li>All services are subject to the terms of Elegant Courier Service or the involved courier partner.</li>
      </ul>
    </section>

    <section title="Pricing and Payments">
      <ul className="list-disc list-inside space-y-1">
        <li>Prices will be displayed based on partner rates.</li>
        <li>All payments must be made as per instructions during booking.</li>
        <li>Additional charges like taxes, duties, or fees will be your responsibility.</li>
      </ul>
    </section>

    <section title="Cancellations and Refunds">
      <p>If you wish to cancel a booking, follow the specified cancellation process. Refunds, if applicable, will be processed by Elegant Courier Service as per their policy.</p>
    </section>

    <section title="Liability and Insurance">
      <ul className="list-disc list-inside space-y-1">
        <li>Courier partners are responsible for safe and timely deliveries.</li>
        <li>CourierWallah does not provide insurance. We recommend arranging insurance for valuable items through your chosen courier partner.</li>
      </ul>
    </section>

    <section title="User Obligations">
      <ul className="list-disc list-inside space-y-1">
        <li>You are responsible for the content of the packages.</li>
        <li>Do not send illegal, prohibited, or hazardous items.</li>
        <li>Do not use the platform to violate laws or disrupt operations.</li>
      </ul>
    </section>

    <section title="Intellectual Property">
      <p>All content on the CourierWallah website is protected by copyright and other laws. This includes logos, texts, images, and trademarks.</p>
    </section>

    <section title="Changes to the Terms and Conditions">
      <p>We may update these terms anytime without prior notice. Continued use of the website implies acceptance of the updated terms.</p>
    </section>

    <section title="Governing Law and Jurisdiction">
      <p>These terms are governed by the laws of India. Disputes shall be subject to the exclusive jurisdiction of Indian courts.</p>
    </section>

    <section title="Contact Information">
      <p>
        By using CourierWallah, you acknowledge that you have read, understood, and agreed to these terms. For any questions, contact us:
      </p>
      <ul className="list-none mt-2 space-y-1">
        <li>Email: <a href="mailto:elegantcourierservice@gmail.com" className="text-blue-600 underline">elegantcourierservice@gmail.com</a></li>
        <li>Email: <a href="mailto:contact@courierwallah.in" className="text-blue-600 underline">contact@courierwallah.in</a></li>
        <li>Phone: <a href="tel:9830517105" className="text-blue-600 underline">9830517105</a></li>
      </ul>
    </section>
  </div>
  )
}
